<?php
/**
 * Created by PhpStorm.
 * User: 54607
 * Date: 2019/5/26
 * Time: 19:21
 */

namespace app\common\moulds;


use think\Model;

/**
 * Class user
 * $property open_id 用户ID
 * @package app\common\moulds
 */
class User extends  Model
{

    const SEX_MALE = 1 ;    //男
    const SEX_FEMALE=2 ;   //女

    const PAGE  =10;

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function extend()
    {
        return $this->hasOne('UserExtend','vip_id');
    }

    /**
     * 获取用户列表
     * @param null $offset
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getUserList($offset=null)
    {
        $page = empty($offset) ?  '1' .','. self::PAGE : $offset.','.self::PAGE;
        $result = self::with('extend')->page($page)->select();
        $result = collection($result)->toArray();
        return $result;
    }

}